site_name: Design docs
# site_url: https://example.com/
repo_url: https://github.com/voloda/notes

plugins:
    - search
    - mermaid2

theme:
  name: material

nav:
    - Root: index.md
      - DO NextGen: do/index.md
        - Child: do/child/index.md

  