site_name: Design docs
# site_url: https://example.com/
repo_url: https://github.com/voloda/notes

plugins:
    - search
    - mermaid2

theme:
  name: material

nav:
    - Home: index.md
    - DO:
      - Home: do/index.md
      - Child:
        - Child: do/child/index.md

  